FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

COPY . .

RUN uv pip install . --system

CMD ["python", "-m", "src.findlybot.main"]
