[project]
name = "findlybot"
version = "0.1.0"
description = "telegram bot for findly"
authors = [{ name = "koloideal", email = "sabatt148@gmail.com" }]
requires-python = "~=3.11"
readme = "README.md"
license = "MIT"
dependencies = [
    "aiogram>=3.13.1,<4",
    "httpx>=0.27.2,<0.28",
    "aiocache>=0.12.3,<0.13",
    "polib>=1.2.0,<2",
    "mysql-connector-python>=9.1.0,<10",
    "dotenv>=0.9.9",
]


[project.optional-dependencies]
dev = [
    "watchfiles>=0.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/findlybot"]
